spring:
#  profiles:
#    active: default
  application:
    name: demo

server:
  ip: 127.0.0.1
  port: 8888
  servlet:
    context-path: /demo

nacos:
  config:
    server-addr: http://192.168.0.200:8848
  discovery:
    server-addr: http://192.168.0.200:8848
    auto-register: true
    register:
      ip: 1.1.1.1
      port: 1
      weight: 0.6D
      healthy: false
      enabled: true
      ephemeral: true
      clusterName: demo
      groupName: DEMO
